name: Test reminder


on:
 
  pull_request:
    branches: [ main ]
  
jobs:
  webhook:
   
    runs-on: ubuntu-latest

   
    steps:
  
    - name: Webhook
    
      with:
        url: "https://apipheny.io"
        json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
   
      
