on:
  workflow_dispatch:
        inputs:
             fromPhoneNumber:
               description: 'Phone number in your Twilio account to send the SMS from'
               required: true
             toPhoneNumber:
                description: 'Phone number to send the SMS to'
                required: true
             message:
                description: 'The message you want to send'
                required: true
             
             
               

