on:
  workflow_dispatch:
 
 
    inputs:
     url:
        description: 'Request URL'
        required: true
     method:
        description: 'Request Method'
        required: false
        default: 'POST'
     contentType:
        description: 'Content Type'
        required: false
     data:
        description: 'Request Body as JSON String'
        required: false
        default: '{}'
     files:
        description: 'Map of absolute file paths as JSON String'
        required: false
        default: '{}'
     file:
        description: 'A single absolute file path'
        required: false
     username:
        description: 'Auth Username'
        required: false
     password:
         description: 'Auth Password'
         required: false
     timeout:
        description: 'Request Timeout in Sec'
        required: false
        default: '5000'
     bearerToken:
        description: 'Bearer Authentication Token'
        required: false
     customHeaders:
        description: 'Custom HTTP Headers'
        required: false
     
    
