on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: Set the value
       id: step_one
       run: |
         echo "action_state=yellow" >> $GITHUB_ENV
     - name: Use the value
       id: step_two
       run: |
        echo "${{ env.action_state }}"
        - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
        - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
