name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run the hello world script
        run: |
         echo Hello, The username is ${{ inputs.username }}
         echo ${{ secrets.token}} 
        
