name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        default: 'john-doe'
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
