on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Make Request
      id: myRequest
      uses: SiyaaJhawar/learning-@main
      with:
       url: "http://yoursite.com/api"

    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
   
